/* Main.ino file generated by New Project wizard
 *
 * Created:   Wed Apr 22 2026
 * Processor: Arduino Uno
 * Compiler:  Arduino AVR (Proteus)
 */

// Peripheral Configuration Code (do not edit)
//---CONFIG_BEGIN---
//---CONFIG_END---


// --- ALGORITMO 5: Multicanal (dos señales independientes) ---
// Pines de adquisición (Fase 3)
const int pin555 = 2; // Canal 1
const int pinFF  = 3; // Canal 2

// Variables de estado y tiempo
bool prev555 = LOW, prevFF = LOW;
unsigned long tUltChange555 = 0, tUltChangeFF = 0;
unsigned long tHigh555 = 0, tLow555 = 0;
unsigned long tHighFF  = 0, tLowFF  = 0;
unsigned long tReporte = 0;

void setup() {
  pinMode(pin555, INPUT);
  pinMode(pinFF, INPUT);
  Serial.begin(9600); 
}

void loop() {
  unsigned long tAhora = millis();

  // --- ALGORITMO 5: Canal 1 (NE555)
  bool cur555 = digitalRead(pin555);
  
  // ALGORITMO 1: Detección de flancos
  if (cur555 != prev555) { 
    
    // ALGORITMO 4: Medición de tiempos HIGH y LOW
    if (cur555 == LOW) {
      tHigh555 = tAhora - tUltChange555;
    } else {
      tLow555 = tAhora - tUltChange555; 
    }
    
    tUltChange555 = tAhora; 
    prev555 = cur555;      
  }

  // --- ALGORITMO 5: Canal 2 (Flip-Flop)
  bool curFF = digitalRead(pinFF);
  
  // ALGORITMO 1: Detección de flancos
  if (curFF != prevFF) {
    
    // ALGORITMO 4: Medición de tiempos HIGH y LOW
    if (curFF == LOW) {
      tHighFF = tAhora - tUltChangeFF; 
    } else {
      tLowFF = tAhora - tUltChangeFF;
    }
    
    tUltChangeFF = tAhora; 
    prevFF = curFF;
  }

  // REPORTE DE RESULTADOS Y CÁLCULOS (FASE 5)
  if (tAhora - tReporte >= 1000) {
    float f555 = 0, d555 = 0, fFF = 0, dFF = 0;
    
    if((tHigh555 + tLow555) > 0) {
       // ALGORITMO 2: Medición de Periodo (Suma de High + Low)
       unsigned long periodo555 = tHigh555 + tLow555;
       
       // ALGORITMO 3: Cálculo de frecuencia
       f555 = 1000.0 / periodo555;
       
       // ALGORITMO 4: Cálculo final de Duty Cycle
       d555 = (float)tHigh555 / periodo555 * 100.0;
    }
    
    if((tHighFF + tLowFF) > 0) {
       // ALGORITMO 2: Periodo
       unsigned long periodoFF = tHighFF + tLowFF;
       
       // ALGORITMO 3: Frecuencia
       fFF = 1000.0 / periodoFF;
       
       // ALGORITMO 4: Duty Cycle
       dFF = (float)tHighFF / periodoFF * 100.0;
    }

    // --- ALGORITMO 5: Visualización de resultados
    Serial.println("--- ANALISIS EXPERIMENTAL ---");
    Serial.print("555   -> Freq: "); Serial.print(f555); Serial.print(" Hz | Duty: "); Serial.print(d555); Serial.println("%");
    Serial.print("F-FLOP-> Freq: "); Serial.print(fFF);  Serial.print(" Hz | Duty: "); Serial.print(dFF);  Serial.println("%");
    tReporte = tAhora;
  }
}